# Generated by Django 3.0.7 on 2020-07-17 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200716_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='enlace',
        ),
    ]
