# Generated by Django 3.0.7 on 2020-07-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_project_enlace'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enlace',
            field=models.URLField(blank=True, null=True),
        ),
    ]
