# Generated by Django 3.0.7 on 2020-07-17 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_enlace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='enlace',
        ),
    ]
